name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Deploy to all EC2 instances
      uses: appleboy/ssh-action@master
      with:
        # Lista de instancias EC2
        hosts: ${{ secrets.EC2_HOSTS }}  # Incluir las 5 IPs/DNS aquí separadas por comas
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd AwsE
          git pull origin main
          sudo mv index.html /var/www/html/
